export const FORGOT_PASSWORD_REQUEST = 'accessRecovery/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'accessRecovery/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'accessRecovery/FORGOT_PASSWORD_ERROR';

export const RESTORE_PASSWORD_REQUEST = 'accessRecovery/RESTORE_PASSWORD_REQUEST';
export const RESTORE_PASSWORD_SUCCESS = 'accessRecovery/RESTORE_PASSWORD_SUCCESS';
export const RESTORE_PASSWORD_ERROR = 'accessRecovery/RESTORE_PASSWORD_ERROR';
