export const REGISTER_ADVERTISER = '/advertiser/REGISTER_ADVERTISER';
export const REGISTER_ADVERTISER_SUCCESS = 'accessRecovery/REGISTER_ADVERTISER_SUCCESS';
export const REGISTER_ADVERTISER_ERROR = 'accessRecovery/REGISTER_ADVERTISER_ERROR';

export const CONFIRM_ADV_REGISTRATION = '/advertiser/CONFIRM_ADV_REGISTRATION';
export const CONFIRM_ADV_REGISTRATION_SUCCESS = 'accessRecovery/CONFIRM_ADV_REGISTRATION_SUCCESS';
export const CONFIRM_ADV_REGISTRATION_ERROR = 'accessRecovery/CONFIRM_ADV_REGISTRATION_ERROR';
