export const REGISTER_ADVERTISER = 'ad-registration/REGISTER_ADVERTISER';
export const REGISTER_ADVERTISER_SUCCESS = 'ad-registration/REGISTER_ADVERTISER_SUCCESS';
export const REGISTER_ADVERTISER_ERROR = 'ad-registration/REGISTER_ADVERTISER_ERROR';

export const CONFIRM_ADV_REGISTRATION = 'ad-registration/CONFIRM_ADV_REGISTRATION';
export const CONFIRM_ADV_REGISTRATION_SUCCESS = 'ad-registration/CONFIRM_ADV_REGISTRATION_SUCCESS';
export const CONFIRM_ADV_REGISTRATION_ERROR = 'ad-registration/CONFIRM_ADV_REGISTRATION_ERROR';

export const CLEAN_ERROR = 'ad-registration/CLEAN_ERROR';
export const SET_DEFAULT_STATE = 'ad-registration/SET_DEFAULT_STATE';
