export const REQUEST_DEVICES = 'REQUEST_DEVICES';
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES';
export const RECEIVE_PAGINATION = 'RECEIVE_PAGINATION';

export const REGISTER_DEVICE = 'REGISTER_DEVICE';
export const CHANGE_DEVICE_STATUS = 'CHANGE_DEVICE_STATUS';
export const CANCEL_DEVICE_REGISTRATION = 'CANCEL_DEVICE_REGISTRATION';
