export const REQUEST_DEVICES = 'REQUEST_DEVICES';
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES';
export const RECEIVE_PAGINATION = 'RECEIVE_PAGINATION';

export const REGISTER_DEVICE = 'REGISTER_DEVICE';
export const RECEIVE_DEVICE_STATUS = 'RECEIVE_DEVICE_STATUS';
export const RECEIVE_DEVICE_SERIAL = 'RECEIVE_DEVICE_SERIAL';
export const CANCEL_DEVICE_REGISTRATION = 'CANCEL_DEVICE_REGISTRATION';
