export const REQUEST_DEVICES = 'REQUEST_DEVICES';
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES';
export const RECEIVE_PAGINATION = 'RECEIVE_PAGINATION';

export const REGISTER_DEVICE = 'REGISTER_DEVICE';
export const CHANGE_DEVICE_STATUS = 'CHANGE_DEVICE_STATUS';
export const CANCEL_DEVICE_REGISTRATION = 'CANCEL_DEVICE_REGISTRATION';

export const REQUEST_ALL_GEO_POINTS = 'REQUEST_ALL_GEO_POINTS';
export const RECEIVE_ALL_GEO_POINTS = 'RECEIVE_ALL_GEO_POINTS';
export const CLEAN_ALL_GEO_POINTS = 'CLEAN_ALL_GEO_POINTS';
