stages:
  - build
  - deploy

services:
  - docker:dind

stable:build:
  image: docker:stable
  tags: [csharp]
  stage: build
  variables:
    DOCKER_FILE_PATH: deployments/docker/Dockerfile
    IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry-gitlab.smarthead.ru
  script:
    - docker build -t $IMAGE -f $DOCKER_FILE_PATH .
    - docker push $IMAGE

stable:deploy:
  stage: deploy
  only: 
    - master
  image: registry-gitlab.smarthead.ru/avastar/smarthead.avastar.kubectl-y:47
  before_script:
    - yc config profile create deployment
    - yc config set service-account-key $SERVICE_ACCOUNT_FILE
    - yc config set folder-id $FOLDER_ID
    - yc config set cloud-id $CLOUD_ID
    - yc managed-kubernetes cluster get-credentials $CLUSTER_NAME --external
    - >
      kubectl create secret docker-registry gitlab-auth-${CI_COMMIT_SHORT_SHA}
      --docker-server="https://registry-gitlab.smarthead.ru"
      --docker-username="gitlab-ci-token"
      --docker-password="$CI_JOB_TOKEN"
  script:
    - cat deployments/k8s/frontend.yaml | sed "s/{{CI_PIPELINE_IID}}/$CI_PIPELINE_IID/g" | sed "s/{{CI_COMMIT_SHORT_SHA}}/$CI_COMMIT_SHORT_SHA/g" | kubectl apply -f -
    - kubectl wait --for=condition=available --timeout=120s deployment/avastar-frontend
  after_script:
    - kubectl delete secret gitlab-auth-${CI_COMMIT_SHORT_SHA}
