export const UPLOAD_FILE = 'UPLOAD_FILE';
export const CHANGE_UPLOAD_STATUS = 'CHANGE_UPLOAD_STATUS';
export const RECEIVE_UPLOADED_CONTENT = 'RECEIVE_UPLOADED_CONTENT';
export const SAVE_XHR = 'SAVE_XHR';
export const CLEAN_XHR = 'CLEAN_XHR';

export const GET_ADVERTISEMENTS_REQUEST = 'ad-manager/GET_ADVERTISEMENTS_REQUEST';
export const GET_ADVERTISEMENTS_SUCCESS = 'ad-manager/GET_ADVERTISEMENTS_SUCCESS';
export const GET_ADVERTISEMENTS_ERROR = 'ad-manager/GET_ADVERTISEMENTS_ERROR';
export const DELETE_ADVERTISEMENT = 'DELETE_ADVERTISEMENT';

export const GET_ADVERTISERS_LIST_REQUEST = 'advertising-management/GET_ADVERTISERS_LIST_REQUEST';
export const GET_ADVERTISERS_LIST_SUCCESS = 'advertising-management/GET_ADVERTISERS_LIST_SUCCESS';
export const GET_ADVERTISERS_LIST_ERROR = 'advertising-management/GET_ADVERTISERS_LIST_ERROR';
export const RESET_ADVERTISERS_LIST = 'advertising-management/RESET_ADVERTISERS_LIST';

export const ADVERTISER_MANAGEMENT_PUT_ERRORS = 'advertisingManagement/ADVERTISER_MANAGEMENT_PUT_ERRORS';
// Очистка ошибок advertisingManagementReducer
export const ADVERTISER_MANAGEMENT_CLEAR_ERRORS = 'advertisingManagement/ADVERTISER_MANAGEMENT_CLEAR_ERRORS';
