export const UPLOAD_FILE = 'UPLOAD_FILE';
export const CHANGE_UPLOAD_STATUS = 'CHANGE_UPLOAD_STATUS';
export const RECEIVE_UPLOADED_CONTENT = 'RECEIVE_UPLOADED_CONTENT';
export const SAVE_XHR = 'SAVE_XHR';
export const CLEAN_XHR = 'CLEAN_XHR';

export const REQUEST_ADVERTISEMENTS = 'REQUEST_ADVERTISEMENTS';
export const RECEIVE_ADVERTISEMENTS = 'RECEIVE_ADVERTISEMENTS';
export const DELETE_ADVERTISEMENT = 'DELETE_ADVERTISEMENT';

export const GET_ADVERTISERS_LIST_REQUEST = 'advertising-management/GET_ADVERTISERS_LIST_REQUEST';
export const GET_ADVERTISERS_LIST_SUCCESS = 'advertising-management/GET_ADVERTISERS_LIST_SUCCESS';
export const GET_ADVERTISERS_LIST_ERROR = 'advertising-management/GET_ADVERTISERS_LIST_ERROR';
export const RESET_ADVERTISERS_LIST = 'advertising-management/RESET_ADVERTISERS_LIST';
