export const UPLOAD_FILE = 'UPLOAD_FILE';
export const CHANGE_UPLOAD_STATUS = 'CHANGE_UPLOAD_STATUS';
export const RECEIVE_UPLOADED_CONTENT = 'RECEIVE_UPLOADED_CONTENT';

export const REQUEST_ADVERTISEMENTS = 'REQUEST_ADVERTISEMENTS';
export const RECEIVE_ADVERTISEMENTS = 'RECEIVE_ADVERTISEMENTS';
export const DELETE_ADVERTISEMENT = 'DELETE_ADVERTISEMENT';
