apiVersion: apps/v1
kind: Deployment
metadata:
  name: avastar-frontend
spec:
  selector:
    matchLabels:
      app: avastar-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: avastar-frontend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: avastar-frontend
        image: registry-gitlab.smarthead.ru/avastar/avastar-frontend:{{CI_PIPELINE_IID}}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: avastar-frontend
spec:
  selector:
    app: avastar-frontend
    tier: frontend
  ports:
  - name: https
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: avastar-frontend-vs
spec:
  hosts:
  - "avastar.smartheadtest.ru"
  gateways:
  - avastar-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: avastar-frontend
        port:
          number: 80
    headers:
      response:
        add:
          Strict-Transport-Security: "max-age=31536000"
        remove:
        - x-envoy-upstream-service-time
