apiVersion: apps/v1
kind: Deployment
metadata:
  name: avastar-frontend
spec:
  selector:
    matchLabels:
      app: avastar-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: avastar-frontend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: avastar-frontend
        image: registry-gitlab.smarthead.ru/avastar/avastar-frontend:{{CI_PIPELINE_IID}}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: avastar-frontend
spec:
  selector:
    app: avastar-frontend
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
