apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        tier: frontend
        track: stable
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
      imagePullSecrets:
      - name: gitlab-auth-${CI_COMMIT_SHORT_SHA}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${APP_NAME}
spec:
  hosts:
  - ${APP_DOMAIN}
  gateways:
  - istio-system.avastar-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ${APP_NAME}
        port:
          number: 80
    headers:
      response:
        add:
          Strict-Transport-Security: "max-age=31536000"
        remove:
        - x-envoy-upstream-service-time
