export const REQUEST_GEO_POINT = 'REQUEST_GEO_POINT';
export const RECEIVE_GEO_POINT = 'RECEIVE_GEO_POINT';

export const REQUEST_ALL_GEO_POINTS = 'REQUEST_ALL_GEO_POINTS';
export const RECEIVE_ALL_GEO_POINTS = 'RECEIVE_ALL_GEO_POINTS';
