// получить список рекламных объявлений
export const GET_ADVERTISEMENTS_LIST_REQUEST = 'advertiser/GET_ADVERTISEMENTS_LIST_REQUEST';
export const GET_ADVERTISEMENTS_LIST_SUCCESS = 'advertiser/GET_ADVERTISEMENTS_LIST_SUCCESS';
export const GET_ADVERTISEMENTS_LIST_ERROR = 'advertiser/GET_ADVERTISEMENTS_LIST_ERROR';
