export const REGISTER_ADVERTISER = 'REGISTER_ADVERTISER';
export const CHANGE_REGISTER_LOADER = 'CHANGE_REGISTER_LOADER';

export const CONFIRM_ADVERTISER_REGISTRATION = 'CONFIRM_ADVERTISER_REGISTRATION';
