export const REQUEST_DEVICE_CONTENT = 'REQUEST_DEVICE_CONTENT';
export const RECEIVE_DEVICE_CONTENT = 'RECEIVE_DEVICE_CONTENT';

export const START_ADVERTISING = 'START_ADVERTISING';
export const STOP_ADVERTISING = 'STOP_ADVERTISING';
export const CHANGE_ADVERTISING_LOADER_STATUS = 'CHANGE_ADVERTISING_LOADER_STATUS';

export const ACTIVATE_DEVICE = 'ACTIVATE_DEVICE';
export const CANCEL_DEVICE_ACTIVATION = 'CANCEL_DEVICE_ACTIVATION';
export const DEACTIVATE_DEVICE = 'DEACTIVATE_DEVICE';
export const CHANGE_DEVICE_STATUS_LOADER = 'CHANGE_DEVICE_STATUS_LOADER';

export const START_MEDIA_STREAM = 'START_MEDIA_STREAM';
export const RECEIVE_MEDIA_STREAM_ID = 'RECEIVE_MEDIA_STREAM_ID';
export const CLEAN_MEDIA_STREAM_ID = 'CLEAN_MEDIA_STREAM_ID';
export const CANCEL_MEDIA_STREAM = 'CANCEL_MEDIA_STREAM';

export const CHANGE_MEDIA_STREAM_LOADER = 'CHANGE_MEDIA_STREAM_LOADER';
export const CHANGE_CURRENT_DEVICE_STATUS = 'CHANGE_CURRENT_DEVICE_STATUS';

export const REQUEST_GEO_POINT = 'REQUEST_GEO_POINT';
export const RECEIVE_GEO_POINT = 'RECEIVE_GEO_POINT';
export const CLEAN_GEO_POINT = 'CLEAN_GEO_POINT';
