export const REQUEST_DEVICE_CONTENT = 'REQUEST_DEVICE_CONTENT';
export const RECEIVE_DEVICE_CONTENT = 'RECEIVE_DEVICE_CONTENT';

export const TOGGLE_ADVERTISING_ON_DEVICE = 'TOGGLE_ADVERTISING_ON_DEVICE';
export const CHANGE_ADVERTISING_LOADER_STATUS = 'CHANGE_ADVERTISING_LOADER_STATUS';

export const TOGGLE_DEVICE_STATUS = 'TOGGLE_DEVICE_STATUS';
export const CHANGE_DEVICE_STATUS_LOADER = 'CHANGE_DEVICE_STATUS_LOADER';

export const REQUEST_MEDIA_STREAM_OPTIONS = 'REQUEST_MEDIA_STREAM_OPTIONS';
export const RECEIVE_MEDIA_STREAM_OPTIONS = 'RECEIVE_MEDIA_STREAM_OPTIONS';
