export const REQUEST_DEVICE_CONTENT = 'REQUEST_DEVICE_CONTENT';
export const RECEIVE_DEVICE_CONTENT = 'RECEIVE_DEVICE_CONTENT';

export const TOGGLE_ADVERTISING_ON_DEVICE = 'TOGGLE_ADVERTISING_ON_DEVICE';

// const TOGGLE_DEVICE_STATUS = 'TOGGLE_DEVICE_STATUS';
